name: Run the tests

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:
  pull_request:

jobs:
  run-initial-tests:
    uses: monk-io/monk-test-infra/.github/workflows/run_initial_tests.yml@main
    secrets: inherit

  create-cluster:
    needs: run-initial-tests
    uses: monk-io/monk-test-infra/.github/workflows/create_cluster.yml@main

  run-tests:
    needs: create-cluster
    runs-on: ubuntu-latest
    container:
      image: gcr.io/monk-releases/monk-ci:latest
      env:
        MONK_LOGIN: ${{ secrets.KIT_TESTING_MONK_USERNAME }}
        MONK_PASS: ${{ secrets.KIT_TESTING_MONK_PASSWORD }}
        MONK_CLI_NO_FANCY: "true"
        MONK_CLI_NO_COLOR: "true"
        MONK_SOCKET: "monkcode://${{needs.create-cluster.outputs.monkcode}}"
        JOB: local/bird/server

    outputs:
      monkcode: ${{needs.create-cluster.outputs.monkcode}}

    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies & setup monkd
        run: |
          apk add gawk curl
          monk login --email "${MONK_LOGIN}" --password "${MONK_PASS}"

      - name: Install KITT
        run: |
          ls -la
          wget https://storage.googleapis.com/monk-releases/kitt/kitt -O /usr/local/bin/kitt
          chmod +x /usr/local/bin/kitt

      - name: Run KITT
        run: |
          /usr/local/bin/kitt lint

      - name: Test - monk load
        run: |
          monk load phpmyadmin.yaml

      - name: Test - monk run
        run: |
          monk run --tag githubrunner "${JOB}"

      - name: Test - monk describe
        run: |
          monk describe "${JOB}"

      - name: Test - monk info
        run: |
          monk info "${JOB}"

      - name: Test - monk ps
        run: |
          monk ps --filter "${JOB}"

      - name: Test - nc 179
        run: |
          set -x
          ENDPOINT=$(monk describe "${JOB}" 2>&1 | awk '/ENDPOINT/ {print $3}' | grep 179)
          H=$(echo $ENDPOINT | cut -f1 -d:)
          P=$(echo $ENDPOINT | cut -f2 -d:)
          nc -w 30 -z $H $P

      - name: Test - monk do show-status
        run: |
          monk do "${JOB}/show-status"

      - name: Test - monk do show-protocols-all
        run: |
          monk do "${JOB}/show-protocols-all"

      - name: Test - monk do show-route
        run: |
          monk do "${JOB}/show-route"

  destroy-cluster:
    needs: run-tests
    if: always()
    uses: monk-io/monk-test-infra/.github/workflows/nuke_cluster.yml@main
    secrets: inherit
    with:
      monkcode: ${{needs.run-tests.outputs.monkcode}}
